### ISSUE TITLE
"Waiting for connection"

### ISSUE THREAD

**Issue by awkahrs** [wtsnz/obs-ios-camera-source#1]
I've installed the plugin for OBS and purchased the iOS app. Everything looks fine except I see "Waiting for connection" and "Settings." How do I get those to go away so I can actually use the iPhone as a webcam? Thanks!

**Comment by wtsnz** [comment]
Hey @awkahrs! 

Thanks for giving it a go 😄 - let's try and get it sorted for you..

So, currently, the connection process is a little more specific than I'd like it to be (I'm working on an update soon to improve it) - I wrote the steps I take normally on the FAQ part of the product website here https://will.townsend.io/products/obs-iphone/install/. 

To save you the trouble, as you've already got everything installed it boils down to:

- Close OBS Studio and the Camera app (make sure to force quit, for now..)
- Connect your iOS device to your computer
- Open Camera for OBS Studio on your iOS Device
- Open OBS Studio on your computer
- Add a new "iOS Camera" source to your scene (if there isn't one)

And all going well, it will connect!

Let me know how you get on 😃

**Comment by awkahrs** [comment]
Tried it again, still no luck. Is there supposed to be something specifically called "iOS Camera" that pops up? So far I've tried to set it up using a Video Capture Device:

![image](https://user-images.githubusercontent.com/38017390/38215853-e60c9e4e-367d-11e8-9e31-9ac55b0c439e.png)

I've also searched for any plugin files that installed, but haven't even seen those! Is it possible I installed an empty plugin folder? (I noticed the installation takes up 236 KB of space, unless it's just a really small plugin?)

![image](https://user-images.githubusercontent.com/38017390/38215967-2fdd8d80-367e-11e8-9a7c-9e293c0dda6b.png)

**Comment by wtsnz** [comment]
Intriguing..!

Inside OBS Studio you should see the 'iOS Camera' source in the plugin area like this:

![obs_21_0_3__mac__-_profile__untitled_-_scenes__untitled_and_desktop_and__waiting_for_connection__ _issue__1_ _wtsnz_obs-ios-camera-source](https://user-images.githubusercontent.com/665916/38216546-38d9ecac-371f-11e8-9479-8f88e7a13fc7.png)

That's what we need to use to connect to the iOS app.

And yes, the plugin is pretty small, 236KB sounds right to me 😄
Using [suspicious package](http://www.mothersruin.com/software/SuspiciousPackage/) you can see where the plugin is installed to: (`/Library/Application Support/obs-studio/plugins/obs-ios-camera-source`)
![screen shot 2018-04-03 at 9 08 44 am](https://user-images.githubusercontent.com/665916/38216388-bb06ed98-371e-11e8-86b4-c84f8f8a18f3.png)

And

**Comment by putiatin** [comment]
Hello @awkahrs 
Due to log of my OBS Studio this problem is due to you don't have these library libavcodec.57.dylib . You need to use brew in terminal to install ffmpeg library (just install brew and than type "brew ffmpeg").

@wtsnz Till ffmpeg library is installed there is no source like iOS Camera in OBS Studio, the log is under this text :)
`23:29:12.368: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so->/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so, 1): Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
23:29:12.368:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so
23:29:12.368:   Reason: image not found
23:29:12.368: 
23:29:12.368: Module '/Library/Application Support/obs-studio/plugins/obs-ios-camera-source/bin/obs-ios-camera-source.so' not loaded`

**Comment by wtsnz** [comment]
Thankyou @putiatin!

I've been working over the last few days on adding support for another decoder (VideoToolbox) that will hopefully solve this issue.

I will look at seeing how I can fix this, as FFMpeg _is_ bundled with OBS Studio itself, and it seems to be pointing at the wrong binary. Thanks again for your help 💯

**Comment by awkahrs** [comment]
I installed Brew and FFMpeg as @putiatin suggested, and it finally worked! Thank you!

**Comment by wtsnz** [comment]
Awesome to hear!

I've figured out why the plugin is pointing at the wrong path for FFMpeg so that will be fixed in the next version :)

Thanks again to the both of you! 😃

**Comment by wtsnz** [comment]
I've released v1.1.0 which fixes the issue and removes the requirement to `brew install ffmpeg` before using the plugin 👍  (https://github.com/wtsnz/obs-ios-camera-source/releases/tag/v1.1.0)

Thanks again to you both @awkahrs, @putiatin 😃

**Comment by dafadness** [comment]
Hello I purchased your app from the store and no matter what I do I cannot get the IOS camera to appear in my OBS.  Im running windows at the moment.  @wtsnz Thanks!
