### ISSUE TITLE
Trouble with app freezing when switching to source in OBS.

### ISSUE THREAD

**Issue by ndimmick** [wtsnz/obs-ios-camera-source#71]
Our church uses a couple iPhones for our lives stream.  One iPhone 7 runs your "Camera for OBS" app and connects to our windows OBS computer via NDI on a dedicated wifi network that only serves the two cameras and the OBS computer.  Recently, we’ve been having lots of trouble getting it to connect, requiring multiple restarts of the app, phone, computer, or wifi connection (no pattern).  The past couple Sundays, the app has frozen upon switching OBS back to its source.  This is causing lots of trouble for our live stream volunteer.  I’m wondering how we could go about troubleshooting what might be happening.  The other iPhone runs EpocCam.

Thanks,
Nick

iPhone 7
iOS 14.4.2
Camera for OBS 3.1.1-79
Windows 10 Home 1909 18363.1440
OBS 26.1.1

**Comment by ndimmick** [comment]
Our first iPhone didn't cause a problem, and our HDMI sources were fine, too. Our "Front iPhone" is running Epoch Cam. The problem "R iPhone" is running "Camera for OBS". Both are connected through a dedicated router that is not connected to the internet. 

This is the log created after the first restart. The operator tried to switch the scene to "R iPhone" and then back to "Front iPhone" after she realized it wasn't working again. This happened at 11:08:49.419
https://obsproject.com/logs/fDvi7GprXOXGTP8r

Any help would be appreciated. This has happened two weeks now. After the first week, I made sure all software was up to date.

**Comment by wtsnz** [comment]
Hey @ndimmick 

Sorry for the delay in getting back to you.

Looking at the log file you've shared, it looks like the issue is related to the NDI plugin as it looks like you're not using the iOS Camera Plugin source. I have since release an update to the iOS app that did fix an outstanding issue with NDI on iOS14 (local network permissions, and an issue where backgrounding, and then resuming the app when in NDI mode would cause the device to transparently stop broadcasting)

If you've not yet found a solution, I'd recommend checking out the NDI sources' [repo and issues](https://github.com/Palakis/obs-ndi/issues).

Let me know if you did figure it out though!
best,
Will

**Comment by ndimmick** [comment]
Thanks, Will.  I was on vacation when your first reply came in, and I forgot to reply until you closed this thread just now.  We have not had issues in the last few weeks, and I don't know if we are running that update version you mentioned.  Hopefully, this is no longer an issue for us.  I appreciate your response.
